# Generated by Django 5.2.14 on 2026-05-31 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=120)),
                ('maker', models.CharField(blank=True, max_length=120)),
                ('material', models.CharField(db_index=True, max_length=120)),
                ('thickness', models.DecimalField(db_index=True, decimal_places=3, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('place', models.CharField(blank=True, max_length=120)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['material', 'thickness', 'width', 'length', 'key'],
                'indexes': [models.Index(fields=['material', 'thickness'], name='inventory_m_materia_0290a1_idx'), models.Index(fields=['key', 'material'], name='inventory_m_key_2f02a4_idx')],
            },
        ),
    ]
